apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "postgresql-backup.fullname" . }}
  labels:
    {{- include "postgresql-backup.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  schedule: {{ .Values.CRON_SCHEDULE }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          labels:
            {{- include "postgresql-backup.selectorLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "postgresql-backup.serviceAccountName" . }}
          restartPolicy: {{ .Values.restartPolicy }}
{{- if .Values.image.imagePullSecrets }}
          imagePullSecrets:
            - name: {{ .Values.image.imagePullSecrets }}
{{- end }}
          containers:
            - name: {{ .Chart.Name }}
              args:
                - {{ .Values.global.postgresql.host }}
                - {{ .Values.global.postgresql.postgresqlUsername }}
                - {{ .Values.global.postgresql.postgresqlPassword }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: CLOUD_SERVICE
                  value: {{ .Values.CLOUD_SERVICE }}
                - name: S3_BUCKET 
                  value: {{ .Values.global.oci_backups_container_name }}
                - name: S3_ACCESS_KEY_ID
                  value: {{ .Values.global.s3_access_key }}
                - name: S3_SECRET_ACCESS_KEY 
                  value: {{ .Values.global.s3_secret_key }}
                - name: S3_REGION 
                  value: {{ .Values.global.region }}
