{{- if .Values.enabled }}
{{- if .Values.envSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nlweb-env
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.envSecret.data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
{{- end }}

