{{- if .Values.nlweb.envSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nlweb-env
type: Opaque
stringData:
{{- range $key, $value := .Values.nlweb.envSecret.data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}

