{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nlweb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nlweb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: qdrant
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333
{{- end }}
