apiVersion: v2
name: additional
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: velero
    version: 8.1.0
    condition: velero.enabled
  - name: volume-autoscaler
    version: 1.0.5
    condition: volume-autoscaler.enabled
  - name: nlweb
    version: 0.0.1
    repository: "file://./charts/nlweb"
    condition: nlweb.enabled
  - name: nlwebflink
    version: 0.0.1
    repository: "file://./charts/nlwebflink"
    condition: nlwebflink.enabled         
