velero:
  enabled: true
  credentials:
    useSecret: true
    secretContents:
      cloud: |
        AZURE_STORAGE_ACCOUNT_NAME: {{ .Values.global.cloud_storage_access_key }}
        AZURE_STORAGE_ACCOUNT_KEY: {{ .Values.global.cloud_storage_secret_key }}
  configuration:
    backupStorageLocation:
      - name: default
        provider: "azure"
        bucket: backups
        config:
          storageAccount: 
          storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_KEY
    volumeSnapshotLocation:
      - name: default
        provider: "azure"
  schedules:
    edcluster-backup:
      disabled: false
      schedule: "0 0 * * *"
      useOwnerReferencesInBackup: false
      template:
        ttl: "240h"
        includedNamespaces:
          - "sunbird"
