[
  {
    "Type": "Numerals Counting",
    "Grade": "1, 2",
    "Level": 0,
    "Level-Description": "1 - digit numbers",
    "Sub-Level": 0,
    "Sub-Level-Description": "Alternate numbers are missing",
    "Expression": "[0 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[2]",
    "BTLO": "R",
    "Difficulty": 1,
    "Description": "Tests the identification of sequence of numbers, when alternate numbers are missing.",
    "Text": "Single digit numbers [0 - 9], Blank in the middle",
    "Question Level Hints": "Think of the numbers from 0 to 9 and check which are missing."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "1, 2",
    "Level": 0,
    "Level-Description": "1 - digit numbers",
    "Sub-Level": 1,
    "Sub-Level-Description": "Predecessors are missing",
    "Expression": "[0 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[1]",
    "BTLO": "R",
    "Difficulty": 2,
    "Description": "Tests the identification of sequence of numbers, when predecessors are missing.",
    "Text": "Single digit numbers [0 - 9], Blank in the first box of each row",
    "Question Level Hints": "Look at the succeeding number and think which number will come before that."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "1, 2",
    "Level": 0,
    "Level-Description": "1 - digit numbers",
    "Sub-Level": 2,
    "Sub-Level-Description": "Successors are missing",
    "Expression": "[0 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[3]",
    "BTLO": "R",
    "Difficulty": 2,
    "Description": "Tests the identification of sequence of numbers, when successors are missing.",
    "Text": "Single digit numbers [0 - 9], Blank in the last box of each row",
    "Question Level Hints": "Think of the numbers from 0 to 9 and check which number will come next."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "1, 2",
    "Level": 0,
    "Level-Description": "1 - digit numbers",
    "Sub-Level": 3,
    "Sub-Level-Description": "Missing single digit numbers",
    "Expression": "[0 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[1,3]",
    "BTLO": "R",
    "Difficulty": 3,
    "Description": "Tests the identification of number sequence in single digit numbers.",
    "Text": "Single digit numbers [0 - 9], Blank in the first and last rows of each row",
    "Question Level Hints": "Think of the numbers from 0 to 9 and check which are missing."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "1, 2",
    "Level": 1,
    "Level-Description": "2 - digit numbers",
    "Sub-Level": 0,
    "Sub-Level-Description": "Alternate numbers are missing without 0 in units digit",
    "Expression": "[1 - 8] [2], [1 - 9][1]",
    "Matrix": "3x3",
    "Editable Boxes": "[2]",
    "BTLO": "R",
    "Difficulty": 3,
    "Description": "Tests the identification of sequence of numbers, when alternate numbers are missing without 0 in units digit.",
    "Text": "Two digit numbers [10 - 99], Blank in the middle. No answer of the form [x0]",
    "Question Level Hints": "Recall the counting numbers and find the number that comes between the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "1, 2",
    "Level": 1,
    "Level-Description": "2 - digit numbers",
    "Sub-Level": 1,
    "Sub-Level-Description": "Numbers with 0 in the units digit",
    "Expression": "[1 - 8] [3], [1 - 8] [6]",
    "Matrix": "3x3",
    "Editable Boxes": "[1]",
    "BTLO": "U",
    "Difficulty": 1,
    "Description": "Tests the identification of sequence of numbers with 0 in the units digit.",
    "Text": "Two digit numbers [10 - 99], Blank in the first box of each row. Atleast one answer should be of the form [x9]",
    "Question Level Hints": "Look at the succeeding number and think which number will come before that."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "1, 2",
    "Level": 1,
    "Level-Description": "2 - digit numbers",
    "Sub-Level": 2,
    "Sub-Level-Description": "Numbers with 1 in the units digit",
    "Expression": "[1 - 8][3], [1 - 8] [6]",
    "Matrix": "3x3",
    "Editable Boxes": "[3]",
    "BTLO": "U",
    "Difficulty": 1,
    "Description": "Tests the identification of sequence of numbers with 1 in the units digit.",
    "Text": "Two digit numbers [10 - 99], Blank in the last box of each row. Atleast one answer should be of the form [x1]",
    "Question Level Hints": "Look at the numbers given and think which number will come next."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "1, 2, 3",
    "Level": 1,
    "Level-Description": "2 - digit numbers",
    "Sub-Level": 3,
    "Sub-Level-Description": "Successors are missing in the range of 10 to 99",
    "Expression": "[1 - 8] [0 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[2, 3]",
    "BTLO": "U",
    "Difficulty": 2,
    "Description": "Tests the identification of sequence of numbers, when successors are missing in the range of 10 to 99.",
    "Text": "Two digit numbers [10 - 99], Blank in the last two boxes of each row.",
    "Question Level Hints": "Recall the counting numbers and find the number that comes after the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "1, 2, 3",
    "Level": 1,
    "Level-Description": "2 - digit numbers",
    "Sub-Level": 4,
    "Sub-Level-Description": "Missing 2 digit numbers",
    "Expression": "[1 - 8] [4], [1 - 8] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[1, 3]",
    "BTLO": "U",
    "Difficulty": 3,
    "Description": "Tests the identification of sequence of numbers within 99.",
    "Text": "Two digit numbers [10 - 99], Blank in the first and last boxes of each row. Answers should be of the form [x0 and x9].",
    "Question Level Hints": "Recall the counting numbers and find the numbers that come before and after the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 2,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 0,
    "Sub-Level-Description": "Numbers in the range upto 500 without missing hundreds",
    "Expression": "[1 - 4] [0 - 8] [1 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[2]",
    "BTLO": "R",
    "Difficulty": 4,
    "Description": "Tests the identification of sequence of 3 digit numbers in the range upto 500 without missing hundreds.",
    "Text": "Three digit numbers [100 - 500], Blank in the middle. No answers of the form [x00].",
    "Question Level Hints": "Recall the counting numbers and find the number that comes between the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 2,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 1,
    "Sub-Level-Description": "Numbers in the range upto 500 with missing hundreds",
    "Expression": "[1 - 3] [9] [4], [1 - 3] [9] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[1]",
    "BTLO": "U",
    "Difficulty": 4,
    "Description": "Tests the identification of sequence of 3 digit numbers in the range upto 500 with missing hundreds.",
    "Text": "Three digit numbers [100 - 500], Blank in the first box of each row. Atleast one answer should be of the form [x00].",
    "Question Level Hints": "Look at the succeeding number and think which number will come before that."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 2,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 2,
    "Sub-Level-Description": "Numbers in the range upto 500 with 9 in the units and tens place",
    "Expression": "[1 - 4] [9] [1], [1 - 3] [9] [4], [1 - 3] [9] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[3]",
    "BTLO": "U",
    "Difficulty": 4,
    "Description": "Tests the identification of sequence of 3 digit numbers in the range upto 500 with 9 in the units and tens place.",
    "Text": "Three digit numbers [100 - 500], Blank in the last box of each row. Atleast one answer should be of the form [x99].",
    "Question Level Hints": "Look at the numbers given and think which number will come next."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 2,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 3,
    "Sub-Level-Description": "Numbers within 500 where successors are missing",
    "Expression": "[1 - 4] [0 - 8] [0 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[2, 3]",
    "BTLO": "U",
    "Difficulty": 4,
    "Description": "Tests the identification of sequence of 3 digit numbers within 500 where successors are missing.",
    "Text": "Three digit numbers [100 - 500], Blank in the last two boxes of each row.",
    "Question Level Hints": "Recall the counting numbers and find the number that comes after the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 2,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 4,
    "Sub-Level-Description": "3 digit numbers missing upto 500",
    "Expression": "[1 - 3] [9] [4], [1 - 3] [9] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[1,3]",
    "BTLO": "U",
    "Difficulty": 5,
    "Description": "Tests the identification of sequence of 3 digit numbers within 500.",
    "Text": "Three digit numbers [100 - 500], Blank in the first and last boxes of each row. Answers should be of the form [x00 and x99].",
    "Question Level Hints": "Recall the counting numbers and find the numbers that come before and after the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 3,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 0,
    "Sub-Level-Description": "Numbers in the range from 500 upto 999 without missing hundreds",
    "Expression": "[5 - 9] [0 - 8] [1 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[2]",
    "BTLO": "R",
    "Difficulty": 4,
    "Description": "Tests the identification of sequence of 3 digit numbers in the range from 500 upto 999 without missing hundreds.",
    "Text": "Three digit numbers [500 - 999], Blank in the middle. No answers of the form [x00].",
    "Question Level Hints": "Recall the counting numbers and find the number that comes between the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 3,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 1,
    "Sub-Level-Description": "Numbers in the range from 500 upto 999 with missing hundreds",
    "Expression": "[5 - 8] [9] [4], [5 - 8] [9] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[1]",
    "BTLO": "U",
    "Difficulty": 4,
    "Description": "Tests the identification of sequence of 3 digit numbers in the range from 500 upto 999 with missing hundreds.",
    "Text": "Three digit numbers [500 - 999], Blank in the first box of each row. Atleast one answer should be of the form [x00].",
    "Question Level Hints": "Look at the succeeding number and think which number will come before that."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 3,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 2,
    "Sub-Level-Description": "Numbers in the range from 500 upto 999 with 9 in the units and tens place",
    "Expression": "[5 - 9] [9] [1], [5 - 8] [9] [4], [5 - 8] [9] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[3]",
    "BTLO": "U",
    "Difficulty": 4,
    "Description": "Tests the identification of sequence of 3 digit numbers in the range from 500 upto 999 with 9 in the units and tens place.",
    "Text": "Three digit numbers [500 - 999], Blank in the last box of each row. Atleast one answer should be of the form [x99].",
    "Question Level Hints": "Look at the numbers given and think which number will come next."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 3,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 3,
    "Sub-Level-Description": "Numbers with range from 500 up to 999 where successors are missing",
    "Expression": "[5 - 9] [0 - 8] [0 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[2, 3]",
    "BTLO": "U",
    "Difficulty": 4,
    "Description": "Tests the identification of sequence of 3 digit numbers with range from 500 up to 999 where successors are missing.",
    "Text": "Three digit numbers [500 - 999], Blank in the last two boxes of each row.",
    "Question Level Hints": "Recall the counting numbers and find the number that comes after the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": "2, 3",
    "Level": 3,
    "Level-Description": "3 - digit numbers",
    "Sub-Level": 4,
    "Sub-Level-Description": "3 digit numbers missing from 500 upto 999",
    "Expression": "[5 - 8] [9] [4], [5 - 8] [9] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[1,3]",
    "BTLO": "U",
    "Difficulty": 5,
    "Description": "Tests the identification of sequence of 3 digit numbers from 500 upto 999.",
    "Text": "Three digit numbers [500 - 999], Blank in the first and last boxes of each row. Answers should be of the form [x00 and x99].",
    "Question Level Hints": "Recall the counting numbers and find the numbers that come before and after the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": 3,
    "Level": 4,
    "Level-Description": "4 - digit numbers",
    "Sub-Level": 0,
    "Sub-Level-Description": "Numbers in the range 9999 without missing thousands",
    "Expression": "[1 - 8] [0 - 9] [0 - 8] [1 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[2]",
    "BTLO": "R",
    "Difficulty": 5,
    "Description": "Tests the identification of sequence of 4 digit numbers in the range 9999 without missing thousands.",
    "Text": "Four digit numbers [1000 - 9999], Blank in the middle. No answers of the form [x000].",
    "Question Level Hints": "Recall the counting numbers and find the number that comes between the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": 3,
    "Level": 4,
    "Level-Description": "4 - digit numbers",
    "Sub-Level": 1,
    "Sub-Level-Description": "Numbers in the range within 9999 with missing thousands",
    "Expression": "[1 - 8] [9] [9] [4], [1 - 8 ][9] [9] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[1]",
    "BTLO": "U",
    "Difficulty": 5,
    "Description": "Tests the identification of sequence of 4 digit numbers in the range within 9999 with missing thousands.",
    "Text": "Four digit numbers [1000 - 9999], Blank in the first box of each row. Atleast one answer should be of the form [x000].",
    "Question Level Hints": "Look at the succeeding number and think which number will come before that."
  },
  {
    "Type": "Numerals Counting",
    "Grade": 3,
    "Level": 4,
    "Level-Description": "4 - digit numbers",
    "Sub-Level": 2,
    "Sub-Level-Description": "Numbers in the range within 999 with 9 in the units, tens and hundreds place",
    "Expression": "[1 - 8] [9] [9] [1], [1 - 8] [9] [9] [4], [1 - 8] [9] [9] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[3]",
    "BTLO": "U",
    "Difficulty": 5,
    "Description": "Tests the identification of sequence of 4 digit numbers in the range within 999 with 9 in the units, tens and hundreds place.",
    "Text": "Four digit numbers [1000 - 9999], Blank in the last box of each row. Atleast one answer should be of the form [x999].",
    "Question Level Hints": "Look at the numbers given and think which number will come next."
  },
  {
    "Type": "Numerals Counting",
    "Grade": 3,
    "Level": 4,
    "Level-Description": "4 - digit numbers",
    "Sub-Level": 3,
    "Sub-Level-Description": "Numbers within 9999 where successors are missing",
    "Expression": "[1 - 9][0 - 9] [0 - 8] [0 - 9]",
    "Matrix": "3x3",
    "Editable Boxes": "[2, 3]",
    "BTLO": "R",
    "Difficulty": 5,
    "Description": "Tests the identification of sequence of 4 digit numbers within 9999 where successors are missing.",
    "Text": "Four digit numbers [1000 - 9999], Blank in the last two boxes of each row.",
    "Question Level Hints": "Recall the counting numbers and find the number that comes after the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": 3,
    "Level": 4,
    "Level-Description": "4 - digit numbers",
    "Sub-Level": 4,
    "Sub-Level-Description": "4 digit numbers missing",
    "Expression": "[1 - 8] [9] [9] [4], [1 - 8] [9] [9] [7]",
    "Matrix": "3x3",
    "Editable Boxes": "[1,3]",
    "BTLO": "U",
    "Difficulty": 5,
    "Description": "Tests the identification of sequence of 4 digit numbers 9999.",
    "Text": "Four digit numbers [1000 - 9999], Blank in the first and last boxes of each row. Answers should be of the form [x000 and x999].",
    "Question Level Hints": "Recall the counting numbers and find the numbers that come before and after the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": 3,
    "Level": 5,
    "Level-Description": "1 - 3 digit numbers",
    "Sub-Level": 0,
    "Sub-Level-Description": "Missing single to 3 digit numbers",
    "Expression": "[1 - 988]",
    "Matrix": "3 x 4",
    "Editable Boxes": 0.6,
    "BTLO": "A",
    "Difficulty": 1,
    "Description": "Tests the identification of sequence of numbers from single to 3 digits.",
    "Text": "Single to three digit numbers, Blank at random.[Can have the 3 x 4 matrix]",
    "Question Level Hints": "Recall the counting numbers and find the numbers that come before and after the given numbers."
  },
  {
    "Type": "Numerals Counting",
    "Grade": 3,
    "Level": 6,
    "Level-Description": "3 - 4 digit numbers",
    "Sub-Level": 0,
    "Sub-Level-Description": "Missing 3 to 4 digit numbers",
    "Expression": "[100 - 9988]",
    "Matrix": "3 x 4",
    "Editable Boxes": 0.6,
    "BTLO": "A",
    "Difficulty": 2,
    "Description": "Tests the identification of sequence of numbers from 3 digits to 4 digits.",
    "Text": "Three to four digit numbers, Blank at random.[Can have the 3 x 4 matrix]",
    "Question Level Hints": "Recall the counting numbers and find the numbers that come before and after the given numbers."
  }
]