apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-yugabytecql-migration-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-yugabytecql-migration
    scope: provisioning
  annotations:
    {{.Values.global.yugabyte.provisioning.annotations | toYaml }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-yugabytecql-migration
    spec:
      restartPolicy: Never
      volumes:
      - name: shared-volume
        emptyDir: {}
      initContainers:
      - name: wait-for-yugabyte
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - "timeout {{ .Values.migration.yugabyte.waitTime }} sh -c 'until nc -z yb-tserver-service {{ .Values.global.yugabyte.port }}; do echo waiting for yugabyte; sleep 10; done'"
        volumeMounts:
        - name: shared-volume
          mountPath: /opt/shared-volume
      - name: clone-migrations
        image: alpine/git
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c']
        args:
        - |
          set -ex
          cd /opt/shared-volume
          export migration_branch={{ default "main" .Values.yugabyte_migration_version }}
          git clone --depth 1 --branch "$migration_branch" https://github.com/chethann007/sunbird-yugabyte-migrations.git /opt/shared-volume/sunbird-yugabyte-migrations
          chmod -R 777 /opt/shared-volume
        volumeMounts:
        - name: shared-volume
          mountPath: /opt/shared-volume
      containers:
      - name: migration
        image: yugabytedb/yugabyte:latest
        imagePullPolicy: IfNotPresent
        command: ['bash', '-c']
        args:
        - |
          set -ex
          export ENV={{ .Values.global.env | default "dev" }}
          export YCQLSH_HOST={{ .Values.global.yugabyte.host }}
          export YCQLSH_PORT={{ .Values.global.yugabyte.port }}
          export YCQLSH_USERNAME="${YCQLSH_USERNAME:-yugabyte}"
          export YCQLSH_PASSWORD="${YCQLSH_PASSWORD:-yugabyte}"
          # run migrations from cloned repo
          cd /opt/shared-volume/sunbird-yugabyte-migrations/sunbird-lern
          chmod +x execute_migrations.sh || true
          ./execute_migrations.sh 
        volumeMounts:
        - name: shared-volume
          mountPath: /opt/shared-volume
  backoffLimit: 30