apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "redis-backup.fullname" . }}
  labels:
    {{- include "redis-backup.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  schedule: {{ .Values.CRON_SCHEDULE }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          labels:
            {{- include "redis-backup.selectorLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "redis-backup.serviceAccountName" . }}
          restartPolicy: {{ .Values.restartPolicy }}
{{- if .Values.image.imagePullSecrets }}
          imagePullSecrets:
            - name: {{ .Values.image.imagePullSecrets }}
{{- end }}
          containers:
            - name: {{ .Chart.Name }}
              command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /root/.oci
                  cat <<EOT > /root/.oci/config
                  [DEFAULT]
                  user={{ .Values.global.user_ocid }}
                  fingerprint={{ .Values.global.user_fingerprint }}
                  tenancy={{ .Values.global.user_tenancy }}
                  region={{ .Values.global.user_region }}
                  key_file={{ .Values.global.user_key_file }}
                  EOT
                  echo "Config file created at /root/.oci/config"
                  cat /root/.oci/config
                  ls -al
                  rm -rf {{ .Values.global.user_key_file }}
                  echo  "{{ .Values.global.user_key_file_pem }}" > {{ .Values.global.user_key_file }}
                  chmod 600 /root/.oci/config {{ .Values.global.user_key_file }}
                  echo "Config and key files created:"
                  ls -al
  
                  backup_date=$(date +%d-%b-%Y-%s)
                  kubectl exec -it redis-master-0 -- redis-cli save
                  kubectl cp redis-master-0:/data/dump.rdb dump.rdb
                  bzip2 dump.rdb
                  mv dump.rdb.bz2 dump-$backup_date.rdb.bz2
                  oci os object put \
                    --bucket-name {{ .Values.global.azure_backups_container_name }} \
                    --name dump-$backup_date.rdb.bz2 \
                    --file "dump-$backup_date.rdb.bz2" \
                    --namespace {{ .Values.global.oci_bucket_namespace }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
