replicaCount: 1
fullname: obsrvbb

provisioningAnnotations: &provisioningAnnotations
  "helm.sh/hook-weight": "-4"

redis: &redis
  enabled: true
  nameOverride: "redis"
  fullnameOverride: "redis"
  auth:
    enabled: false
  host: "redis-master"
  port: 6379
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  replica:
    replicaCount: 0
  master:
    persistence:
      size: 25Gi

elasticsearch: &es
  enabled: true
  nameOverride: "elasticsearch"
  fullnameOverride: "elasticsearch"
  host: "elasticsearch"
  port: 9200
  image:
    registry: docker.io
    repository: bitnami/elasticsearch
    tag: 7.10.2
    digest: ""
  master:
    masterOnly: false
    replicaCount: 1
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    heapSize: 2G
    persistence:
      size: 25Gi
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    enabled: false
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  provisioning:
    annotations: *provisioningAnnotations
  sysctlImage:
    registry: sunbirded.azurecr.io
    repository: bitnami-shell-archived
    tag: 11-debian-11-r54


zookeeper: &zookeeper
  fullnameOverride: zookeeper
  nameOverride: zookeeper
  host: "zookeeper"
  port: 2181
  persistence:
    size: 25Gi

kafka: &kafka
  # zookeeper: *zookeeper
  enabled: true
  nameOverride: "kafka"
  fullnameOverride: "kafka"
  # clientProtocol: PLAINTEXT
  host: "kafka-controller-headless"
  port: 9092
  image:
    registry: "docker.io"
    repository: sanketikahub/kafka
    tag: "4.0.0"
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  persistence:
    size: 25Gi
  provisioning:
    nameOverride: "provisioning"
    fullnameOverride: "provisioning"
    annotations:
      "helm.sh/hook-weight": "-4"
    replicationFactor: 1
    numPartitions: 1
    topics:
    - name: "{{ .Values.global.env }}.telemetry.audit"
    - name: "{{ .Values.global.env }}.learning.graph.events"
    - name: "{{ .Values.global.env }}.nlweb.ingest"
    parallel: 1
  listeners:
    client:
      protocol: PLAINTEXT
  controller:
      protocol: PLAINTEXT
  interbroker:
      protocol: PLAINTEXT
  external:
      protocol: PLAINTEXT
  sasl:
    enabledMechanisms: ""
    interBrokerMechanism: ""
    controllerMechanism: ""
  tls:
    autoGenerated:
      enabled: false
    existingSecret: ""

superset:
  enabled: true
  image:
    repository: sunbirded.azurecr.io/superset
    tag: release-7.0.0
    pullPolicy: Always

yugabyte: &yugabyte
  enabled: true
  nameOverride: "yugabyte"
  fullnameOverride: "yugabyte"
  host: "yb-tserver-service" 
  port: 9042
  postgresql_port: 5433
  databases:
    - name: "keycloak"
    - name: "quartz"
    - name: "userorg"
    - name: "enc-keys"
    - name: "registry"

  image:
    registry: yugabytedb
    repository: yugabyte
    tag: 2025.2.0.0-b131 
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  provisioning:
    annotations: *provisioningAnnotations  
  persistence:
    size: 25Gi  
  # Force single replica for Yugabyte masters and tservers (override subchart defaults)
  replicas:
    master: 3
    tserver: 3
  username: yugabyte  
  password: yugabyte    

env: &env
default: "dev"
global:
  redis: *redis
  zookeeper: *zookeeper
  kafka: *kafka
  yugabyte: *yugabyte

