replicaCount: 1
fullname: obsrvbb

provisioningAnnotations: &provisioningAnnotations
  "helm.sh/hook-weight": "-4"

zookeeper: &zookeeper
  fullnameOverride: zookeeper
  nameOverride: zookeeper
  host: "zookeeper"
  port: 2181
  persistence:
    size: 25Gi

kafka: &kafka
  zookeeper: *zookeeper
  enabled: true
  nameOverride: "kafka"
  fullnameOverride: "kafka"
  clientProtocol: PLAINTEXT
  host: "kafka"
  port: 9092
  image:
    registry: sunbirded.azurecr.io
    repository: kafka
    tag: 3.3.1-debian-11-r25
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  persistence:
    size: 25Gi
  provisioning:
    nameOverride: "provisioning"
    fullnameOverride: "provisioning"
    annotations:
      "helm.sh/hook-weight": "-4"
    replicationFactor: 1
    numPartitions: 1
    topics:
    - name: "{{ .Values.global.env }}.nlweb.ingest"
    - name: "{{ .Values.global.env }}.telemetry.ingest"
    parallel: 1

      
superset:
  enabled: true

yugabyte: &yugabyte
  enabled: true
  nameOverride: "yugabyte"
  fullnameOverride: "yugabyte"
  host: "yb-tserver-service" 
  port: 9042
  postgresql_port: 5433
  databases:
    - name: "superset"

  image:
    registry: yugabytedb
    repository: yugabyte
    tag: 2025.2.0.0-b131 
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  provisioning:
    annotations: *provisioningAnnotations  
  persistence:
    size: 25Gi  
  # Force single replica for Yugabyte masters and tservers (override subchart defaults)
  replicas:
    master: 3
    tserver: 3
  username: yugabyte  
  password: yugabyte    

env: &env
default: "dev"
global:
  zookeeper: *zookeeper
  kafka: *kafka
  yugabyte: *yugabyte

