{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ . }}
          backend:
            service:
              name: {{ include "common.names.fullname" $ }}
              port:
                name: http
        {{- end }}
    {{- end }}
{{- end }}
