# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: DeveloperTools
  licenses: Apache-2.0
  images: |
    - name: keycloak
      image: docker.io/bitnami/keycloak:24.0.3-debian-12-r3
    - name: keycloak-config-cli
      image: docker.io/bitnami/keycloak-config-cli:5.12.0-debian-12-r2
apiVersion: v2
appVersion: 24.0.3
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
  - keycloak
  - access-management
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: keycloak
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/keycloak
version: 21.1.2
