{{- if .Values.rbac.create -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: {{ if .Values.rbac.clusterWideAccess }}ClusterRoleBinding{{ else }}RoleBinding{{ end }}
metadata:
  name: {{ include "volume-autoscaler.fullname" . }}
  namespace: {{ (include "base.namespace" $) }}
  labels:
{{- include "labels" . | indent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.rbac.clusterWideAccess }}ClusterRole{{ else }}Role{{ end }}
  name: {{ include "volume-autoscaler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "volume-autoscaler.fullname" . }}
    namespace: {{ (include "base.namespace" $) }}
{{- end -}}
