{
 "title": "Dashboard-All",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Kubernetes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ready Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Non-Ready Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  { "title": "Infra Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Traffic : Requests / Sec (Heuristic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[2m]))",
     "legendFormat": "Today"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total[5m] offset 1d))  ",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total[5m] offset 1w))  ",
     "legendFormat": "Last Week Same Day"
    }
   ]
  },
  {
   "title": "status count by percentage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests_total[${__range_s}s])) by (status)",
     "legendFormat": "count"
    },
    {
     "expr": "sum(increase(nginx_http_requests_total[${__range_s}s])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[${__range_s}s])) * 100"
    }
   ]
  },
  {
   "title": "Traffic : Requests / Sec - Kubernetes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Nginx total Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_connections) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "4xx Error % Kubernetes-1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|5..\"}[1m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[1m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "5xx Error % kubernetes-1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|4..\"}[1m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[1m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Load avg on VM's",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(host) * on (instance) group_left(nodename) node_load1",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(node_load1) * on (instance) group_left(nodename) node_uname_info{job=~\".*node-exporter\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "5xx APIs rate over 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_status_count{status_code=~\"5..\"}[5m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Kafka servers Data Disk utilization % ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{ mountpoint=\"/data\", job=~\".*node-exporter\"} - node_filesystem_free_bytes{ mountpoint=\"/data\"}) * 100 / node_filesystem_size_bytes{mountpoint=\"/data\"}  * on (instance) group_left(nodename) node_uname_info )  by (nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk utilization %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{ mountpoint=\"/\", job=~\".*node-exporter\"} - node_filesystem_free_bytes{ mountpoint=\"/\"}) * 100 / node_filesystem_size_bytes{mountpoint=\"/\"}  * on (instance) group_left(nodename) node_uname_info )  by (nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Core Kube Volumes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-operator-grafana\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-operator-grafana\"})\n)",
     "legendFormat": "prometheus-operator-grafana(Used Space)"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-operator-grafana\"})\n",
     "legendFormat": "prometheus-operator-grafana(Free Space)"
    },
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"})\n)",
     "legendFormat": "prometheus-data-volume(Used Space)"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"})\n",
     "legendFormat": "prometheus-data-volume(Free Space)"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"}\n  -\n  kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"}\n)\n/\nkubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"}\n* 100"
    }
   ]
  },
  {
   "title": "node count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": ":kube_pod_info_node_count:" }
   ]
  },
  {
   "title": "DP Kube Volumes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-operator-grafana\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-operator-grafana\"})\n)",
     "legendFormat": "prometheus-operator-grafana(Used Space)"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-operator-grafana\"})\n",
     "legendFormat": "prometheus-operator-grafana(Free Space)"
    },
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"})\n)",
     "legendFormat": "prometheus-data-volume(Used Space)"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"})\n",
     "legendFormat": "prometheus-data-volume(Free Space)"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 48 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"}\n  -\n  kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"}\n)\n/\nkubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring\", persistentvolumeclaim=\"prometheus-sunbird-monitoring-prometheus-db-prometheus-sunbird-monitoring-prometheus-0\"}\n* 100"
    }
   ]
  }
 ]
}